// BNF only used to generate types & lexer for highlight
{
  elementTypeHolderClass="main.java.intellij.gleam.GleamTypes"
  tokenTypeClass="main.scala.intellij.gleam.lang.GleamTokenType"

  tokens = [
    IMPORT='import'
    LET='let'
    PUB='pub'
    FN='fn'
    USE='use'
    CASE='case'
    TYPE='type'

    CONCAT='<>'
    PIPE='|>'
    TUPLE="#"
    LEFT_ARROW='<-'
    RIGHT_ARROW='->'

    LEFT_PARENTHESIS='('
    RIGHT_PARENTHESIS=')'
    LEFT_BRACKET='{'
    RIGHT_BRACKET='}'
    LEFT_ARRAY_BRACKET='['
    RIGHT_ARRAY_BRACKET=']'

    NUMBER_VALUE='regexp:\d+(\.\d*)?'
    STRING_VALUE="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"

    LOWER_CASE_TERM='regexp:\p{Lower}\w*'
    UPPER_CASE_TERM='regexp:\p{Upper}\w*'

    LINE_COMMENT='regexp:(//)[^\r\n]*'
  ]
}

root ::= !<<eof>>